name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: RUSTFLAGS="--cfg production" cargo build --release --target $TARGET
